name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Workflow
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Restore Nuget
        run: nuget restore Hto3.KubernetesDefinition.sln
      - name: Build
        run: MSBuild -p:Configuration=Release -p:DebugSymbols=False -p:DebugType=none -p:GenerateDocumentation=False -p:SyncfusionLicense=${{ secrets.SYNCFUSION }} -p:OutputPath=bin\Release Hto3.KubernetesDefinition.UI\Hto3.KubernetesDefinition.UI.csproj
      - name: Remove debug symbols
        working-directory: Hto3.KubernetesDefinition.UI\bin\Release
        run: rm *.xml, *.pdb
      - name: Pack Portable
        working-directory: Hto3.KubernetesDefinition.UI\bin\Release
        run: 7z a -t7z -mx9 Release.7z *.config *.exe *.dll
      - name: Pack Installer
        working-directory: Hto3.KubernetesDefinition.UI\bin\Release
        run: makensis /V4 ..\..\..\installer.nsi
      - name: Define version
        run: Get-Date -Format "VERSION=yyyy-MM-dd" >> $env:GITHUB_ENV
      - name: Create github release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            Hto3.KubernetesDefinition.UI\bin\Release\Release.7z
            installer.exe